enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "latest"

[YouTube]
app-name = "YouTube"
rv-brand = "ReVanced Extended"
build-mode = "module"
version = "auto"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
excluded-patches = "'Alternative thumbnails' 'Bypass image region restrictions' 'Change form factor' 'Swipe controls' 'Translations for YouTube' 'Enable debug logging'"
included-patches = "'Theme'"

[YouTube-Music]
app-name = "YouTube Music"
rv-brand = "ReVanced Extended"
build-mode = "module"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
excluded-patches = "'Bypass image region restrictions' 'Translations for YouTube Music' 'Enable debug logging'"
